# More details of how to configure this file can be found in this link
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "04:00"
      timezone: Asia/Jerusalem
    target-branch: develop
    open-pull-requests-limit: 50
    commit-message:
      prefix: "[dependabot]"
    assignees:
      - eladheller
    reviewers:
      - eladheller
